export const REMINDERS = {
  not_found: 'Lembrete não encontrado.',
  invalid_list: 'A lista selecionada não existe mais.',
  back_to_lists: 'Voltar para listas',
  list_title: (listName: string) => `Lembretes de ${listName}`,
  placeholder: {
    title: 'Título do Lembrete',
    date: 'YYYY-MM-DD',
    time: 'HH:mm',
  },
  button: {
    create: 'Novo Lembrete',
    update: 'Editar Lembrete',
  },
  empty_list: 'Nenhum lembrete para esta lista.',
  enable_button: 'Ativar',
  disable_button: 'Desativar',
  edit_button: 'Editar',
  remove_button: 'Remover',
  remove_title: 'Remover lembrete',
  remove_message: 'Deseja remover este lembrete?',
  permission_title: 'Permissão de notificação negada',
  permission_denied_message:
    'O lembrete foi salvo, mas sem permissão não será notificado em segundo plano.',
  center_title: 'Central de lembretes',
  center_hint: 'Revise lembretes de todas as listas com filtros rápidos.',
  center_empty: 'Nenhum lembrete encontrado para este filtro.',
  unknown_list: 'Lista removida',
  in_list: (listName: string) => `Lista: ${listName}`,
  open_list_button: 'Abrir lista',
  open_list_reminders_button: 'Lembretes',
  open_center_button: 'Central de lembretes',
  pending_title: 'Lembretes pendentes sem notificação',
  pending_alert_title: 'Lembrete Vencido',
  pending_alert_message: (title: string, listName: string) =>
    `O lembrete "${title}" da lista "${listName}" está vencido.\nDeseja desativar ou apagar?`,
  notification_body: 'Abra sua lista para revisar os itens.',
  filter_label: {
    all: 'Todos',
    enabled: 'Ativos',
    disabled: 'Desativados',
    overdue: 'Vencidos',
  },
}
