export const REMINDERS = {
  list_required: 'Lembrete precisa estar vinculado a uma lista existente.',
  invalid_datetime: 'Data/hora inválida. Use data no formato YYYY-MM-DD e hora no formato HH:mm.',
  not_found: 'Lembrete não encontrado.',
  invalid_list: 'A lista selecionada não existe mais.',
  back_to_lists: 'Voltar para listas',
  list_title: (listName: string) => `Lembretes da lista: ${listName}`,
  list_hint: 'Crie lembretes locais e ative notificações quando quiser.',
  title_placeholder: 'Título do lembrete',
  date_placeholder: 'YYYY-MM-DD',
  time_placeholder: 'HH:mm',
  create_button: 'Criar lembrete',
  update_button: 'Salvar edição',
  cancel_edit_button: 'Cancelar edição',
  empty_list: 'Nenhum lembrete para esta lista.',
  enable_button: 'Ativar',
  disable_button: 'Desativar',
  edit_button: 'Editar',
  remove_button: 'Remover',
  remove_title: 'Remover lembrete',
  remove_message: 'Deseja remover este lembrete?',
  status_scheduled: 'Ativo e agendado',
  status_not_scheduled: 'Ativo, mas não agendado',
  status_disabled: 'Desativado',
  status_overdue: 'Vencido',
  permission_title: 'Permissão de notificação negada',
  permission_denied_message:
    'O lembrete foi salvo, mas sem permissão não será notificado em segundo plano.',
  center_title: 'Central de lembretes',
  center_hint: 'Revise lembretes de todas as listas com filtros rápidos.',
  center_empty: 'Nenhum lembrete encontrado para este filtro.',
  unknown_list: 'Lista removida',
  in_list: (listName: string) => `Lista: ${listName}`,
  open_list_button: 'Abrir lista',
  open_list_reminders_button: 'Lembretes',
  open_center_button: 'Central de lembretes',
  pending_title: 'Lembretes pendentes sem notificação',
  notification_body: 'Abra sua lista para revisar os itens.',
  filter_label: {
    all: 'Todos',
    enabled: 'Ativos',
    disabled: 'Desativados',
    overdue: 'Vencidos',
  },
}
